spring:
  profiles:
    active: dev

logging:
  file:
    name: ${user.dir}/log/LMS_log.log
  level:
    leejaewoo.server.book : info
    leejaewoo.server.bookcategory : info
    leejaewoo.server.category : info
    leejaewoo.server.global : info
    leejaewoo.server.member : info
    leejaewoo.server.rental : info